var localization = {
    "af":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Afrikaans",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "yes":"Yes",
        "cancel":"Cancel"
    },
    "sq":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Albanian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "am":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Amharic",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ar":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Arabic",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "hy":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Armenian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "az":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Azerbaijan",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ba":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Bashkir",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "eu":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Basque",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "be":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Belarusian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "bn":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Bengali",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "bs":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Bosnian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "bg":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Bulgarian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ca":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Catalan",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ceb":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Cebuano",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "zh":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Chinese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "hr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Croatian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "cs":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Czech",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "da":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Danish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "nl":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Dutch",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "en":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"English",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "eo":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Esperanto",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "et":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Estonian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "fi":{
        "title":"Sanaselityspeli",
        "timeOut":"Aika loppui!",
        "help":"Paina aloita",
        "next":"Seuraava",
        "skip":"Ohita",
        "start":"Aloita",
        "continue":"Jatka",
        "reset":"Nollaa",
        "language":"Finnish",
        "languageDropdown":"Kieli",
        "exitConfirmation":"Lopeta peli?",
        "resetConfirmation":"Nollaa peli?",
        "cancel":"Peruuta",
        "yes":"Kyllä"
    },
    "fr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"French",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "gl":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Galician",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ka":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Georgian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "de":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"German",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "el":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Greek",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "gu":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Gujarati",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ht":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Haitian (Creole)",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "he":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Hebrew",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mrj":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Hill Mari",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "hi":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Hindi",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "hu":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Hungarian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "is":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Icelandic",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "id":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Indonesian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ga":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Irish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "it":{
        "title":"Explain it!",
        "timeOut":"Tempo scaduto!",
        "help":"Premi start",
        "next":"Prossimo",
        "skip":"Passo",
        "start":"Start",
        "continue":"Avanti",
        "reset":"Azzera",
        "language":"Italian",
        "languageDropdown":"Lingue",
        "exitConfirmation":"Uscita?",
        "resetConfirmation":"Azzera gioco?",
        "cancel":"Cancellare",
        "yes":"Si"
    },
    "ja":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Japanese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "jv":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Javanese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "kn":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Kannada",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "kk":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Kazakh",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ko":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Korean",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ky":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Kyrgyz",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "la":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Latin",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "lav":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Latvian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "lt":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Lithuanian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mk":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Macedonian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mg":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Malagasy",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ms":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Malay",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ml":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Malayalam",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mi":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Maori",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Marathi",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mhr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Mari",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "mn":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Mongolian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ne":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Nepali",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "no":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Norwegian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "pap":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Papiamento",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "fa":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Persian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "pl":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Polish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "pt":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Portuguese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "pa":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Punjabi",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ro":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Romanian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ru":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Russian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "gd":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Scottish Gaelic",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "sr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Serbian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "si":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Sinhala",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "sk":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Slovakian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "sl":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Slovenian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "es":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Spanish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "su":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Sundanese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "sw":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Swahili",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "sv":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Swedish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "tl":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Tagalog",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "tg":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Tajik",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ta":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Tamil",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "tt":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Tatar",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "te":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Telugu",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "th":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Thai",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "tr":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Turkish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "udm":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Udmurt",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "uk":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Ukrainian",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "ur":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Urdu",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "uz":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Uzbek",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "vi":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Vietnamese",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "cy":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Welsh",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "xh":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Xhosa",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    },
    "yi":{
        "title":"Explain it!",
        "timeOut":"Time out!",
        "help":"Press start",
        "next":"Next",
        "skip":"Skip",
        "start":"Start",
        "continue":"Continue",
        "reset":"Reset",
        "language":"Yiddish",
        "languageDropdown":"Language",
        "exitConfirmation":"Are you sure you want to exit?",
        "resetConfirmation":"Reset game?",
        "cancel":"Cancel",
        "yes":"Yes"
    }
};